### ISSUE TITLE
Connect!

### ISSUE THREAD

**Issue by cyberhasse** [shadowedice/StockTicker#1]
Hi!
Trying to get this to work..
All i get in terminal window is:

WiFi connected
IP address: 
192.168.1.186
HTTP/1.1 404 Not FoundUnexpected HTTP response $0.00 0.00
Current ticker is: 0

Regards.
//Cyberhasse

**Comment by shadowedice** [comment]
Hey cyberhasse,

I took a look into your issue and it looks like the API I was using then is now inactive. I ran into this issue where API endpoints for stock information would be closed off randomly while making different code projects. To help mitigate the issue for the stock ticker, I made https://github.com/shadowedice/ScrollingDisplay to display a scrolling message from data that is sent via from a udp packet with json formatting. That way I have a server that can push the messages to the display and I don't need to update the arduino code to interact with the different API endpoints. I only need to update the API code (in whatever language I desire) on the server side. The only downside to this approach is it is no longer contained all within the arduino.

If you are interested in trying to get the code to work again it looks like they moved their API to https://iexcloud.io/ It looks like they still over a free option but it is limited in the data that you can retrieve. The code would also need to be updated to support the updates to their API.

-ShadowedIce
